apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carbonj-p1-data-carbonj-p1-0
  namespace: carbonj
  labels:
    app: carbonj
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2-us-east-1a
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carbonj-p2-data-carbonj-p2-0
  namespace: carbonj
  labels:
    app: carbonj
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2-us-east-1b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G
